// <auto-generated />
using System;
using DailyChecklist.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DailyChecklist.Infrastructure.Migrations
{
    [DbContext(typeof(DailyChecklistContext))]
    [Migration("20260815021108_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DailyChecklist.Domain.Entities.ActivePeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RoutineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("RoutineId");

                    b.ToTable("ActivePeriods", (string)null);
                });

            modelBuilder.Entity("DailyChecklist.Domain.Entities.GroupTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GroupItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupItemId");

                    b.ToTable("GroupTasks");
                });

            modelBuilder.Entity("DailyChecklist.Domain.Entities.Routine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Routines", (string)null);
                });

            modelBuilder.Entity("DailyChecklist.Domain.Entities.RoutineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("RoutineId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoutineId");

                    b.ToTable("RoutineItems", (string)null);

                    b.HasDiscriminator<string>("ItemType").HasValue("RoutineItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DailyChecklist.Domain.Entities.GroupItem", b =>
                {
                    b.HasBaseType("DailyChecklist.Domain.Entities.RoutineItem");

                    b.HasDiscriminator().HasValue("Group");
                });

            modelBuilder.Entity("DailyChecklist.Domain.Entities.TaskItem", b =>
                {
                    b.HasBaseType("DailyChecklist.Domain.Entities.RoutineItem");

                    b.HasDiscriminator().HasValue("Task");
                });

            modelBuilder.Entity("DailyChecklist.Domain.Entities.ActivePeriod", b =>
                {
                    b.HasOne("DailyChecklist.Domain.Entities.Routine", "Routine")
                        .WithMany("ActivePeriods")
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Routine");
                });

            modelBuilder.Entity("DailyChecklist.Domain.Entities.GroupTask", b =>
                {
                    b.HasOne("DailyChecklist.Domain.Entities.GroupItem", "GroupItem")
                        .WithMany("GroupTasks")
                        .HasForeignKey("GroupItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupItem");
                });

            modelBuilder.Entity("DailyChecklist.Domain.Entities.RoutineItem", b =>
                {
                    b.HasOne("DailyChecklist.Domain.Entities.Routine", "Routine")
                        .WithMany("Items")
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Routine");
                });

            modelBuilder.Entity("DailyChecklist.Domain.Entities.Routine", b =>
                {
                    b.Navigation("ActivePeriods");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("DailyChecklist.Domain.Entities.GroupItem", b =>
                {
                    b.Navigation("GroupTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
